### ISSUE TITLE
Add animation for IE8 and IE9

### ISSUE THREAD

**Issue by desandro** [metafizzy/outlayer#15]
Outlayer animation uses CSS transitions. Browsers that do not support transitions get no animation. If you'd like to see animation for IE8 and IE9, please +1.

**Comment by MichielMunckhof** [comment]
+1

**Comment by creunabo** [comment]
+1

**Comment by roeycohen** [comment]
+1

**Comment by sculove** [comment]
+1

**Comment by qiumohanyu** [comment]
+1

**Comment by desandro** [comment]
I'll be dropping support for IE8 and IE9 at the end of the year. Sorry, but this feature request will not be fulfilled. Putting this one to rest :ghost:
