### ISSUE TITLE
Wiredep inclusion

### ISSUE THREAD

**Issue by loganetherton** [metafizzy/outlayer#32]
It appears as though the change to "main" introduced in [this commit](https://github.com/metafizzy/outlayer/commit/dcdeaf1491511cfa030af2eacea75b0babbcd8a0) causes errors when masonry is included via wiredep. Reverting "main" back to an array of both item.js and outlayer.js gets rid of the error shown below.

```
Uncaught TypeError: Cannot read property 'Item' of undefined -- outlayer.js:42
Uncaught TypeError: Cannot read property 'create' of undefined -- masonry.js:43
```

**Comment by desandro** [comment]
This is part of a larger discussion over what `bower.json` `main` should be. I'm currently settling the issue in bower/bower.json-spec#43. `outlayer.js` is the main entry point.

**Comment by gablabelle** [comment]
@desandro @loganetherton Hello, FYI I have the same problem today after `bower install --save isotope`

![screen shot 2015-09-11 at 13 56 53](https://cloud.githubusercontent.com/assets/1565793/9822205/140284f2-588d-11e5-8e76-a5f090595057.png)

**Comment by JulianLaval** [comment]
+1!

**Comment by desandro** [comment]
Closing as a duplicate of #33
