### ISSUE TITLE
Firefox ( latest ) : Type error

### ISSUE THREAD

**Issue by prisme** [metafizzy/outlayer#34]
Hi ! and first of all thanks a lot for publishing so many useful public libraries : )

I've included Packery in my application, as a commonJS module.

Upon instantiation, I get this (blocking) error in the devtools console : 
     `TypeError: CSS2Properties doesn't have an indexed property setter.`

I've traced it back to https://github.com/metafizzy/outlayer/blob/master/outlayer.js#L144 

the 2nd argument of this function call being a string, FF won't add it as a property of `this.element.style`, which is a CSS2Properties object : https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration

I just commented out this line to get my project to work.
I wish I could propose a better way to do this right now and submit a pull request.
I hope this issue will be useful anyway.

best.

**Comment by desandro** [comment]
Thanks for reporting this issue.

> the 2nd argument of this function call being a string, 

Sounds like the root problem is that `containerStyle` is set to a string, when it should be set to an object, like `{ position: 'relative' }`. If that's the case, then this isn't a bug. If you have a test case I can take a look.

**Comment by prisme** [comment]
thanks for your reply, I'll try using an object instead.
I know I should have joined a link to a jsfiddle test-case, thanks for looking into it anyway !
