### ISSUE TITLE
Why don't you support packaged files or cdn url?

### ISSUE THREAD

**Issue by sculove** [metafizzy/outlayer#46]
I made some component using outlayer.
I'd like to share this component to many people.
But I couldn't do it becacuse outlayer does not support cdn or packaged files.

cf. the masonry supports packaged files and cdn url.
https://github.com/desandro/masonry/tree/master/dist
http://cdnjs.com/libraries/masonry

so I send the pr #44 
please merged.....

**Comment by desandro** [comment]
Outlayer is the foundation of a layout library, but it doesn't have much functionality by itself. I recommend packaging Outlayer and its dependencies with your custom layout, like I do with Masonry, Isotope, and Packery.
