### ISSUE TITLE
Feature: chaining

### ISSUE THREAD

**Issue by marcobiedermann** [metafizzy/outlayer#53]
return `this` on methods to allow chaining:

```js
masonry.layout()
  .reloadItems();
```

I know the example above could be accomplished by using `.appended()` but there might be some useful cases for chaining.

**Comment by desandro** [comment]
Hello! Thanks for this suggestion.

Actually, I'm not a fan of chaining for most of my libraries. It makes sense when you're making multiple manipulations on a string or an array. But you're not often triggering multiple methods in succession, or least, you shouldn't be.  I appreciate your input but I'll have to pass on this one.

**Comment by marcobiedermann** [comment]
@desandro 
Alright, thank you David for your opinion and explanation.
